### ISSUE TITLE
Update a changelog de release  0.0.2

### ISSUE THREAD

**Issue by pablomassa** [ladiaria/utopia-cms#17]
En el release https://github.com/ladiaria/utopia-cms/releases/tag/0.0.2

Agregar al changelog https://github.com/ladiaria/utopia-cms/blob/main/CHANGELOG.md

En el bullet del feature "Lista de lectura", este texto "Feature details at https://ayuda.ladiaria.com.uy/que-es-la-lista-de-lectura/ (Spanish)"

**Comment by anibalpacheco** [comment]
this is related to https://github.com/ladiaria/utopia-cms/pull/16

**Comment by anibalpacheco** [comment]
updated
