### ISSUE TITLE
Update AUTHORS.md including people who have contributed in the past

### ISSUE THREAD

**Issue by anibalpacheco** [ladiaria/utopia-cms#2]
Ignacio Toledo
José Callero
Bruno Sarlo
Miguel Lezama
Guillermo Colmenero
Alvaro Mouriño
Eduardo Roldán
Diego García

**Comment by anibalpacheco** [comment]
do we need a special redaction format for this @gabelula ?

**Comment by gabelula** [comment]
What do you mean? I already added some names We can add those names too. I added contact information but we do not have to.

**Comment by anibalpacheco** [comment]
@gabelula I mean that those people listed here in this issue have contributed in the past, not under "the actual utopía project", I was thinking to put them at the end under a subtitle like "## Authors who contributed in the past" (or similar)

**Comment by gabelula** [comment]
ok. Here https://github.com/ladiaria/utopia-cms/pull/5
