### ISSUE TITLE
Installation document for LightGallery is wrong when pulling from main branch

### ISSUE THREAD

**Issue by despinoUY** [ladiaria/utopia-cms#6]
**Describe the bug**
When pulling the LightGallery module during the installation process documented in the file INSTALL.md is requesting to do that from main branch which does not exist. Related with this issue: https://github.com/ladiaria/lightGallery/issues/1

**To Reproduce**
1. Clone the LightGallery repository as documented:
`user@host:~/utopia-cms $ git clone -b main https://github.com/ladiaria/lightGallery static/lightGallery`
2. Error message states that main branch does not exist.

**Expected behavior**
`master` branch in LightGallery should be renamed to `main`.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
https://github.com/ladiaria/lightGallery/issues/1

**Comment by anibalpacheco** [comment]
I will give priority to this issue soon, thanks for reporting @despinoUY

**Comment by anibalpacheco** [comment]
done. closing
